openapi: 3.0.3
info:
  title: Minerva
  description: The entrypoint to all your books and notes of Minerva.
  version: 0.1.0
servers:
  - url: https://laravel.minerva.com/api
    description: local laravel api
  - url: https://nodejs.minerva.com/api
    description: local nodejs api
tags:
  - name: users
  - name: books
  - name: notes


paths:
  /users:
    post:
      operationId: createUser
      summary: create user
      description: Create a new user based on a unique email address and a password.
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          description: The user has been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/id'
        400:
          $ref: '#/components/responses/badRequest'
  /users/log-in:
    post:
      operationId: logIn
      summary: log in
      description: Log a user in based on a unique email address and a password.
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        200:
          description: The user was logged in.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/id'
        400:
          $ref: '#/components/responses/badRequest'
  /users/{userId}/books:
    get:
      operationId: getBooks
      summary: get books
      description: Get all books of a user's library.
      tags:
        - books
      parameters:
        - $ref: '#/components/parameters/userIdInPath'
      security:
        - bearerAuth: []
      responses:
        200:
          description: An array with the user's books is returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/book'
        401:
          $ref: '#/components/responses/unauthorized'
        404:
          $ref: '#/components/responses/notFound'
    post:
      operationId: addBook
      summary: add book
      description: Add a new book to a user's library.
      tags:
        - books
      parameters:
        - $ref: '#/components/parameters/userIdInPath'
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book'
      responses:
        201:
          description: The book has been added to the user's library.
        400:
          $ref: '#/components/responses/badRequest'
        401:
          $ref: '#/components/responses/unauthorized'
        404:
          $ref: '#/components/responses/notFound'
        409:
          description: The book is already present in the user's library.
  /users/{userId}/books/{isbn}:
    delete:
      operationId: deleteBook
      summary: delete book
      description: Delete a book from a user's library.
      tags:
        - books
      parameters:
        - $ref: '#/components/parameters/userIdInPath'
        - $ref: '#/components/parameters/isbnInPath'
      security:
        - bearerAuth: []
      responses:
        204:
          description: The book has been deleted form the user's library.
        401:
          $ref: '#/components/responses/unauthorized'
        404:
          $ref: '#/components/responses/notFound'
  /users/{userId}/books/{isbn}/notes:
    get:
      operationId: getNotes
      summary: get notes
      description: Get all notes made to a book.
      tags:
        - notes
      parameters:
        - $ref: '#/components/parameters/userIdInPath'
        - $ref: '#/components/parameters/isbnInPath'
      security:
        - bearerAuth: []
      responses:
        200:
          description: An array with the notes of a user's book is returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/note'
        401:
          $ref: '#/components/responses/unauthorized'
        404:
          $ref: '#/components/responses/notFound'
    post:
      operationId: addNote
      summary: add note
      description: Add a note to a book.
      tags:
        - notes
      parameters:
        - $ref: '#/components/parameters/userIdInPath'
        - $ref: '#/components/parameters/isbnInPath'
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                note:
                  type: string
              required:
                - note
      responses:
        201:
          description: The note has been added to the user's book.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/id'
        400:
          $ref: '#/components/responses/badRequest'
        401:
          $ref: '#/components/responses/unauthorized'
        404:
          $ref: '#/components/responses/notFound'
  /users/{userId}/books/{isbn}/notes/{noteId}:
    delete:
      operationId: deleteNote
      summary: delete note
      description: Delete a note made to a book.
      tags:
        - notes
      parameters:
        - $ref: '#/components/parameters/userIdInPath'
        - $ref: '#/components/parameters/isbnInPath'
        - $ref: '#/components/parameters/noteIdInPath'
      security:
        - bearerAuth: []
      responses:
        204:
          description: The note has been deleted from the user's book.
        401:
          $ref: '#/components/responses/unauthorized'
        404:
          $ref: '#/components/responses/notFound'


components:
  schemas:
    id:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
      required:
        - id
    user:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    book:
      type: object
      properties:
        isbn:
          type: string
      required:
        - isbn
    note:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        note:
          type: string
      required:
        - id
        - note

  parameters:
    userIdInPath:
      name: userId
      in: path
      description: The ID of the user.
      required: true
      schema:
        type: integer
        minimum: 1
    isbnInPath:
      name: isbn
      in: path
      description: The ISBN of the book.
      required: true
      schema:
        type: string
    noteIdInPath:
      name: noteId
      in: path
      description: The ID of the note.
      required: true
      schema:
        type: integer
        minimum: 1

  responses:
    badRequest:
      description: The request contains an invalid body.
    unauthorized:
      description: The request requires authentication.
    notFound:
      description: The requested resource was not found.

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
